[package]
name = "ncmaz_faust_sidecar"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
include_dir = "0.7"
once_cell = "1.19"
wee_alloc = "0.4"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
